// Reduce an HTML string to readable plain text. Post excerpts and meta
// descriptions must never render raw markup, but a blank excerpt is
// auto-generated by the backend from the content — and content that begins
// with an image or other tags yields an excerpt full of HTML. Strip tags,
// decode the common entities, and collapse whitespace before display.
// Regex-based so it is safe in both server and client components.
export function htmlToPlainText(html: string): string {
  return html
    .replace(/<[^>]*>/g, " ")
    // A backend-truncated excerpt can end mid-tag (no closing ">"); drop it.
    .replace(/<[^>]*$/, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/\s+/g, " ")
    .trim();
}

export function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export function formatPostDate(dateString: string): string {
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "2-digit",
    year: "numeric",
  }).format(new Date(dateString));
}

const RELATIVE_TIME_UNITS: [Intl.RelativeTimeFormatUnit, number][] = [
  ["year", 60 * 60 * 24 * 365],
  ["month", 60 * 60 * 24 * 30],
  ["day", 60 * 60 * 24],
  ["hour", 60 * 60],
  ["minute", 60],
];

const relativeTimeFormatter = new Intl.RelativeTimeFormat("en-US", {
  numeric: "always",
});

export function formatRelativeTime(dateString: string): string {
  const diffSeconds = Math.round(
    (new Date(dateString).getTime() - Date.now()) / 1000,
  );

  if (Math.abs(diffSeconds) < 60) return "just now";

  for (const [unit, secondsInUnit] of RELATIVE_TIME_UNITS) {
    if (Math.abs(diffSeconds) >= secondsInUnit) {
      return relativeTimeFormatter.format(
        Math.round(diffSeconds / secondsInUnit),
        unit,
      );
    }
  }

  return "just now";
}
